LoginMVC/Controllers/CategoryController.cs
using LoginMVC.Data;
using LoginMVC.Models;
using LoginMVC.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace LoginMVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ApplicationDbContext _context;
        public CategoryController(ICategoryRepository categoryRepository, ApplicationDbContext context)
        {
            _categoryRepository = categoryRepository;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var Categories = await _categoryRepository.GetCategoriesAsync();
            return View(Categories);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        public async Task<IActionResult> EditCategory(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = await _categoryRepository.GetCategory(id);
            ViewBag.Name = category.Name;
            ViewBag.DisplayOrder = category.DisplayOrder;
            return View(category);
        }
        public async Task<IActionResult> DeleteCategory(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = await _categoryRepository.GetCategory(id);
            return View(category);
        }
        [HttpPost, ActionName("DeleteCategory")]
        public async Task<IActionResult> DeleteCategoryPOST(Category category)
        {
            _context.Categories.Remove(category);
            await _categoryRepository.Save();
            TempData["delete"] = "Delete successfully";
            return RedirectToAction("Index");
        }
        [HttpPost("Category/EditCategory")]
        public async Task<IActionResult> EditCategory(Category category)
        {
            if (category.DisplayOrder <= 0 || category.DisplayOrder > 100)
            {
                ModelState.AddModelError("displayOrder", "Display order should be between 1 to 100");
            }
            if (category.Name.IsNullOrEmpty())
            {
                ModelState.AddModelError("name", "Name cannot be empty");
            }
            if (ModelState.IsValid)
            {
                _categoryRepository.Update(category);
                await _categoryRepository.Save();
                TempData["update"] = "Update category successfully";
                return RedirectToAction("Index");
            }
            ViewBag.Name = category.Name;
            ViewBag.DisplayOrder = category.DisplayOrder;
            return View();
        }


        [HttpPost("Category/CreateCategory")]
        public async Task<IActionResult> CreateCategory(string name, int displayOrder)
        {
            if (displayOrder <= 0 || displayOrder > 100)
            {
                ModelState.AddModelError("displayOrder", "Display order should be between 1 to 100");
            }
            if (name.IsNullOrEmpty())
            {
                ModelState.AddModelError("name", "Name cannot be empty");
            }
            if (ModelState.IsValid)
            {
                var category = _categoryRepository.CreateCategory(name, displayOrder);
                await _categoryRepository.AddCategory(category);
                await _categoryRepository.Save();
                TempData["create"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            ViewBag.Name = name;
            ViewBag.DisplayOrder = displayOrder;
            return View();
        }
    }
}

LoginMVC/Controllers/CompanyController.cs
using LoginMVC.Models;
using LoginMVC.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LoginMVC.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyRepository _companyRepository;
        public CompanyController(ICompanyRepository companyRepository)
        {
            _companyRepository= companyRepository;
        }
        public async Task<IActionResult> Index()
        {
            var companys = await _companyRepository.GetCompanys();
            return View(companys);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost("Company/Create")]
        public async Task<IActionResult> Create(Company company)
        {
            await _companyRepository.AddCompany(company);
            _companyRepository.Save();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0 || id == null)
            {
                return RedirectToAction("Index");
            }
            var company = await _companyRepository.GetCompany(id);
            return View(company);
        }
        [HttpPost("Company/Edit")]
        public  IActionResult Edit(Company company)
        {
            _companyRepository.Update(company);
            TempData["update"] = "Update category successfully";
            _companyRepository.Save();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0 || id == null)
            {
                return RedirectToAction("Index");
            }
            var company = await _companyRepository.GetCompany(id);
            return View(company);
        }
        [HttpPost("Company/Delete")]
        public IActionResult Delete(Company company)
        {
            _companyRepository.Delete(company);
            _companyRepository.Save();
            TempData["delete"] = "Delete successfully";
            return RedirectToAction("Index");
        }
    }
}

LoginMVC/Controllers/ShoppingCartController.cs
using LoginMVC.Data;
using LoginMVC.DTO;
using LoginMVC.Models;
using LoginMVC.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace LoginMVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartRepository _shoppingCartRepository;
        private readonly ApplicationDbContext _context;
        public ShoppingCartController(IShoppingCartRepository shoppingCartRepository, ApplicationDbContext context)
        {
            _shoppingCartRepository= shoppingCartRepository;
            _context= context;
        }
        public async Task<IActionResult> Index()
        {
            var cliamsIdentity = (ClaimsIdentity)User.Identity;
            var userId = cliamsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            CartDTO cart = new CartDTO()
            {
                ShoppingCartList = await _context.ShoppingCarts.Where(u => u.IdentityUserId == userId).Include(u => u.Product).ToListAsync()
            };
            double totalOrder = 0;
            double totalPrice = 0;
            foreach (var item in cart.ShoppingCartList)
            {
                totalOrder += item.Count;
                totalPrice += item.Product.Price * item.Count;
            }
            cart.TotalOrder = totalOrder;
            cart.TotalPrice = totalPrice;
            return View(cart);
        }
        public async Task<IActionResult> Edit(int productId)
        {

            var cliamsIdentity = (ClaimsIdentity)User.Identity;
            var userId = cliamsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            var shoppingCart = await _context.ShoppingCarts.Where(u => u.IdentityUserId == userId && u.ProductId == productId).FirstOrDefaultAsync();
            return View(shoppingCart);
        }
        [HttpPost("ShoppingCart/Edit")]
        public async Task<IActionResult> Edit(ShoppingCart shoppingCart)
        {
            _context.ShoppingCarts.Update(shoppingCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int productId)
        {

            var cliamsIdentity = (ClaimsIdentity)User.Identity;
            var userId = cliamsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            var shoppingCart = await _context.ShoppingCarts
                .Where(u => u.IdentityUserId == userId && u.ProductId == productId)
                .Include(u => u.Product)
                .FirstOrDefaultAsync();
            return View(shoppingCart);
        }
        [HttpPost("ShoppingCart/Delete")]
        public async Task<IActionResult> Delete(ShoppingCart shoppingCart)
        {
            _context.ShoppingCarts.Remove(shoppingCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

LoginMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuyComicMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BuyComicMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuyComicMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Roles.Role_Company))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                            </li>    
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                                    <i class="bi bi-cart"></i>
                                </a>
                            </li>
                        }

                        @if (User.IsInRole(Roles.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Dropdown
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top fixed-bottom text-muted">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Thanasiri
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LoginMVC/Views/Shared/_Notifications.cshtml
@if (TempData["create"] != null)
{
        <script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <script type="text/javascript">toastr.success('@TempData["create"]')</script>
}
@if (TempData["update"] != null)
{
        <script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <script type="text/javascript">toastr.info('@TempData["update"]')</script>
}
@if (TempData["delete"] != null)
{
        <script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <script type="text/javascript">toastr.info('@TempData["delete"]')</script>
}